### PR TITLE
Switch to scoped @prettier package

### PR DESCRIPTION
**Pull request by azz**
Just published current code as `0.0.0-development` - https://www.npmjs.com/package/@prettier/python

### CODE REVIEW

**Comment by taion** [comment]
Namespacing, neat!

**Comment by j-f1** [comment]
> Namespaces are one honking great idea -- let's do more of those!

From [the zen of Python](https://zen-of-python.info/namespaces-are-one-honking-great-idea--lets-do-more-of-those.html#19). ([official link](https://www.python.org/dev/peps/pep-0020/#the-zen-of-python))

**Comment by taion** [comment]
Yes that's actually a lie. Namespaced packages in Python are a dumpster fire and in general people who have used them move away from using them. They're very much "0/10 would not recommend" there.

It's not anybody's fault or anything – it's just the way Python package resolution works, because the package name for importing doesn't connect in any necessary way to the package name on PyPI. Makes hostile forks easier, though.

**Comment by taion** [comment]
(They're great in the npm ecosystem, though!)

**Pull request merged**
